<a href="https://colab.research.google.com/github/akanupam/ML_learings/blob/main/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
np

<module 'numpy' from '/usr/local/lib/python3.12/dist-packages/numpy/__init__.py'>

#Normal Arrays

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.full(10,2.7)

array([2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7])

In [ ]:
a = np.array([1,23,44,])

In [ ]:
a[2]

np.int64(44)

In [ ]:
a[1] = 99

In [ ]:
a

array([ 1, 99, 44])

In [ ]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

#Multi-dimensional Array

In [ ]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
n = np.array([
    [1,2,3],
    [2,3,4]
]
)

In [ ]:
n[0,1] = 20

In [ ]:
n

array([[ 1, 20,  3],
       [ 2,  3,  4]])

In [ ]:
n[0]

array([ 1, 20,  3])

In [ ]:
n[1] = [1,2,3]

In [ ]:
n

array([[ 1, 20,  3],
       [ 1,  2,  3]])

In [ ]:
n[:,1]

array([20,  2])

#Randomly generated Arrays

In [ ]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [ ]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [ ]:
np.random.seed(2)
np.random.randint(low = 0,high = 100, size = (5,3))

array([[40, 15, 72],
       [22, 43, 82],
       [75,  7, 34],
       [49, 95, 75],
       [85, 47, 63]])

#Element-wise operations

In [ ]:
a = np.arange(5)

In [ ]:
a

array([0, 1, 2, 3, 4])

In [ ]:
a + 1

array([1, 2, 3, 4, 5])

In [ ]:
b = a * 2

In [ ]:
b

array([0, 2, 4, 6, 8])

In [ ]:
a+b

array([ 0,  3,  6,  9, 12])

#Comparison Operations

In [ ]:
a

array([0, 1, 2, 3, 4])

In [ ]:
a>=2

array([False, False,  True,  True,  True])

In [ ]:
b

array([0, 2, 4, 6, 8])

In [ ]:
a>=b

array([ True, False, False, False, False])

In [ ]:
b[b>a]

array([2, 4, 6, 8])

#Summarizing Operations

In [ ]:
a

array([0, 1, 2, 3, 4])

In [ ]:
a.min()

np.int64(0)

In [ ]:
a.sum()

np.int64(10)

In [ ]:
a.mean()

np.float64(2.0)

In [ ]:
a.max()

np.int64(4)