<a href="https://colab.research.google.com/github/akanupam/ML_learings/blob/main/Random_forest_using_penguins_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df = sns.load_dataset('penguins')
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female

In [4]:
df.shape

(344, 7)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    object 
 1   island             344 non-null    object 
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object 
dtypes: float64(4), object(3)
memory usage: 18.9+ KB


In [6]:
df.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [8]:
df.dropna(inplace=True)
df.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [9]:
df.sex.unique()

array(['Male', 'Female'], dtype=object)

In [10]:
pd.get_dummies(df.sex).head()

Female   Male
0   False   True
1    True  False
2    True  False
4    True  False
5   False   True

In [11]:
sex = pd.get_dummies(df.sex, drop_first = True)
sex.head()


Male
0   True
1  False
2  False
4  False
5   True

In [13]:
df.island.unique()

array(['Torgersen', 'Biscoe', 'Dream'], dtype=object)

In [14]:
pd.get_dummies(df.island).head()

Biscoe  Dream  Torgersen
0   False  False       True
1   False  False       True
2   False  False       True
4   False  False       True
5   False  False       True

In [16]:
island = pd.get_dummies(df.island, drop_first = True)
island.head()

Dream  Torgersen
0  False       True
1  False       True
2  False       True
4  False       True
5  False       True

In [17]:
new_data = pd.concat([df,island,sex],axis=1)
new_data.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
4  Adelie  Torgersen            36.7           19.3              193.0   
5  Adelie  Torgersen            39.3           20.6              190.0   

   body_mass_g     sex  Dream  Torgersen   Male  
0       3750.0    Male  False       True   True  
1       3800.0  Female  False       True  False  
2       3250.0  Female  False       True  False  
4       3450.0  Female  False       True  False  
5       3650.0    Male  False       True   True

In [29]:
# new_data.drop(['sex','island'],axis=1, inplace=True)
new_data.head()


species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0  Adelie            39.1           18.7              181.0       3750.0   
1  Adelie            39.5           17.4              186.0       3800.0   
2  Adelie            40.3           18.0              195.0       3250.0   
4  Adelie            36.7           19.3              193.0       3450.0   
5  Adelie            39.3           20.6              190.0       3650.0   

   Dream  Torgersen   Male  
0  False       True   True  
1  False       True  False  
2  False       True  False  
4  False       True  False  
5  False       True   True

In [30]:
Y = new_data.species
Y.head()

0    Adelie
1    Adelie
2    Adelie
4    Adelie
5    Adelie
Name: species, dtype: object

In [31]:
Y.unique()

array(['Adelie', 'Chinstrap', 'Gentoo'], dtype=object)

In [32]:
Y = Y.map({'Adelie': 0, 'Chinstrap': 1, 'Gentoo': 2})
Y.head()

0    0
1    0
2    0
4    0
5    0
Name: species, dtype: int64

In [33]:
new_data.drop('species',axis=1,inplace=True)
new_data.head()

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  Dream  \
0            39.1           18.7              181.0       3750.0  False   
1            39.5           17.4              186.0       3800.0  False   
2            40.3           18.0              195.0       3250.0  False   
4            36.7           19.3              193.0       3450.0  False   
5            39.3           20.6              190.0       3650.0  False   

   Torgersen   Male  
0       True   True  
1       True  False  
2       True  False  
4       True  False  
5       True   True

In [34]:
X = new_data

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=0)

In [36]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(233, 7)
(100, 7)
(233,)
(100,)


In [37]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=5, criterion='entropy',random_state=0)
classifier.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=5, random_state=0)

In [38]:
y_pred = classifier.predict(X_test)
y_pred

array([0, 0, 2, 0, 0, 0, 1, 2, 2, 1, 2, 0, 0, 1, 0, 0, 2, 0, 1, 0, 0, 0,
       2, 2, 2, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 1, 0, 1, 0, 2, 2, 0, 0,
       0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 2, 0, 1, 0, 2, 0, 0,
       2, 2, 1, 2, 2, 1, 2, 1, 0, 2, 0, 2, 0, 2, 1, 2, 2, 2, 1, 2, 1, 0,
       0, 2, 2, 0, 2, 0, 2, 0, 2, 0, 2, 2])

In [39]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
cm = confusion_matrix(y_test,y_pred)
cm

array([[48,  0,  0],
       [ 2, 14,  0],
       [ 0,  0, 36]])

In [40]:
accuracy_score(y_test,y_pred)

0.98

In [41]:
classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n           0       0.96      1.00      0.98        48\n           1       1.00      0.88      0.93        16\n           2       1.00      1.00      1.00        36\n\n    accuracy                           0.98       100\n   macro avg       0.99      0.96      0.97       100\nweighted avg       0.98      0.98      0.98       100\n'

Trying differnt number of trees and gini criteria


In [42]:
classifier = RandomForestClassifier(n_estimators=7, criterion='gini',random_state=0)
classifier.fit(X_train,y_train)

RandomForestClassifier(n_estimators=7, random_state=0)

In [43]:
y_pred = classifier.predict(X_test)
y_pred

array([0, 0, 2, 0, 0, 0, 1, 2, 2, 1, 2, 0, 0, 1, 0, 0, 2, 0, 1, 0, 0, 0,
       2, 2, 2, 2, 0, 0, 0, 0, 0, 1, 0, 1, 0, 2, 1, 0, 1, 0, 2, 2, 0, 0,
       0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 2, 0, 1, 0, 2, 0, 0,
       2, 2, 1, 2, 2, 1, 2, 1, 0, 2, 0, 2, 0, 2, 1, 2, 2, 2, 1, 2, 1, 0,
       0, 2, 2, 0, 2, 0, 2, 0, 2, 0, 2, 2])

In [44]:
accuracy_score(y_test,y_pred)

0.99